export const product = [
    [
        {
          "id": "P001",
          "name": "Classic White T-Shirt",
          "description": "A timeless white t-shirt made from soft, breathable cotton.",
          "size": ["S", "M", "L", "XL"],
          "brand": "BasicWear",
          "price": 19.99,
          "img": ["https://example.com/images/white-tshirt-front.jpg", "https://example.com/images/white-tshirt-back.jpg"],
          "discount": 10,
          "category": "T-Shirts"
        },
        {
          "id": "P002",
          "name": "Slim Fit Jeans",
          "description": "Stylish slim fit jeans perfect for a casual look.",
          "size": ["28", "30", "32", "34", "36"],
          "brand": "DenimCo",
          "price": 49.99,
          "img": ["https://example.com/images/slim-fit-jeans-front.jpg", "https://example.com/images/slim-fit-jeans-back.jpg"],
          "discount": 15,
          "category": "Jeans"
        },
        {
          "id": "P003",
          "name": "Denim Jacket",
          "description": "Classic denim jacket with a modern twist.",
          "size": ["M", "L", "XL"],
          "brand": "DenimCo",
          "price": 79.99,
          "img": ["https://example.com/images/denim-jacket-front.jpg", "https://example.com/images/denim-jacket-back.jpg"],
          "discount": 20,
          "category": "Jackets"
        },
        {
          "id": "P004",
          "name": "Black Hoodie",
          "description": "Cozy black hoodie with a soft fleece lining.",
          "size": ["S", "M", "L", "XL"],
          "brand": "ComfyClothes",
          "price": 39.99,
          "img": ["https://example.com/images/black-hoodie-front.jpg", "https://example.com/images/black-hoodie-back.jpg"],
          "discount": 5,
          "category": "Hoodies"
        },
        {
          "id": "P005",
          "name": "Checked Shirt",
          "description": "Casual checked shirt perfect for a weekend outing.",
          "size": ["S", "M", "L", "XL"],
          "brand": "FlannelHouse",
          "price": 29.99,
          "img": ["https://example.com/images/checked-shirt-front.jpg", "https://example.com/images/checked-shirt-back.jpg"],
          "discount": 10,
          "category": "Shirts"
        },
        {
          "id": "P006",
          "name": "Sports Joggers",
          "description": "Comfortable joggers for sports and casual wear.",
          "size": ["M", "L", "XL"],
          "brand": "Sportify",
          "price": 34.99,
          "img": ["https://example.com/images/sports-joggers-front.jpg", "https://example.com/images/sports-joggers-back.jpg"],
          "discount": 8,
          "category": "Joggers"
        },
        {
          "id": "P007",
          "name": "Casual Polo Shirt",
          "description": "Breathable polo shirt for a smart-casual look.",
          "size": ["S", "M", "L", "XL"],
          "brand": "ClassicWear",
          "price": 24.99,
          "img": ["https://example.com/images/polo-shirt-front.jpg", "https://example.com/images/polo-shirt-back.jpg"],
          "discount": 10,
          "category": "Polos"
        },
        {
          "id": "P008",
          "name": "Formal Dress Pants",
          "description": "Elegant dress pants suitable for any formal occasion.",
          "size": ["30", "32", "34", "36", "38"],
          "brand": "SuitUp",
          "price": 59.99,
          "img": ["https://example.com/images/dress-pants-front.jpg", "https://example.com/images/dress-pants-back.jpg"],
          "discount": 12,
          "category": "Pants"
        },
        {
          "id": "P009",
          "name": "Leather Jacket",
          "description": "Stylish leather jacket for a bold look.",
          "size": ["M", "L", "XL"],
          "brand": "LeatherLux",
          "price": 129.99,
          "img": ["https://example.com/images/leather-jacket-front.jpg", "https://example.com/images/leather-jacket-back.jpg"],
          "discount": 18,
          "category": "Jackets"
        },
        {
          "id": "P010",
          "name": "Graphic T-Shirt",
          "description": "Trendy graphic t-shirt for everyday wear.",
          "size": ["S", "M", "L", "XL"],
          "brand": "UrbanStyle",
          "price": 22.99,
          "img": ["https://example.com/images/graphic-tshirt-front.jpg", "https://example.com/images/graphic-tshirt-back.jpg"],
          "discount": 5,
          "category": "T-Shirts"
        },
        {
          "id": "P011",
          "name": "V-Neck Sweater",
          "description": "Soft V-neck sweater for a smart casual look.",
          "size": ["S", "M", "L", "XL"],
          "brand": "CozyKnits",
          "price": 44.99,
          "img": ["https://example.com/images/v-neck-sweater-front.jpg", "https://example.com/images/v-neck-sweater-back.jpg"],
          "discount": 10,
          "category": "Sweaters"
        },
        {
          "id": "P012",
          "name": "Cargo Shorts",
          "description": "Durable cargo shorts with multiple pockets.",
          "size": ["S", "M", "L", "XL"],
          "brand": "AdventureGear",
          "price": 35.99,
          "img": ["https://example.com/images/cargo-shorts-front.jpg", "https://example.com/images/cargo-shorts-back.jpg"],
          "discount": 15,
          "category": "Shorts"
        },
        {
          "id": "P013",
          "name": "Biker Leather Jacket",
          "description": "Edgy biker jacket made from premium leather.",
          "size": ["M", "L", "XL"],
          "brand": "RiderZ",
          "price": 149.99,
          "img": ["https://example.com/images/biker-jacket-front.jpg", "https://example.com/images/biker-jacket-back.jpg"],
          "discount": 20,
          "category": "Jackets"
        },
        {
          "id": "P014",
          "name": "Striped Shirt",
          "description": "Classic striped shirt for a smart-casual ensemble.",
          "size": ["S", "M", "L", "XL"],
          "brand": "SharpLines",
          "price": 32.99,
          "img": ["https://example.com/images/striped-shirt-front.jpg", "https://example.com/images/striped-shirt-back.jpg"],
          "discount": 8,
          "category": "Shirts"
        },
        {
          "id": "P015",
          "name": "Graphic Sweatshirt",
          "description": "Comfy sweatshirt with a bold graphic design.",
          "size": ["M", "L", "XL"],
          "brand": "ArtWear",
          "price": 39.99,
          "img": ["https://example.com/images/graphic-sweatshirt-front.jpg", "https://example.com/images/graphic-sweatshirt-back.jpg"],
          "discount": 12,
          "category": "Sweatshirts"
        },
        {
          "id": "P016",
          "name": "Tailored Suit Jacket",
          "description": "Elegant tailored suit jacket for formal events.",
          "size": ["M", "L", "XL"],
          "brand": "EliteTailors",
          "price": 199.99,
          "img": ["https://example.com/images/suit-jacket-front.jpg", "https://example.com/images/suit-jacket-back.jpg"],
          "discount": 10,
          "category": "Suits"
        },
        {
          "id": "P017",
          "name": "Chino Pants",
          "description": "Comfortable and versatile chino pants for everyday wear.",
          "size": ["30", "32", "34", "36", "38"],
          "brand": "EverydayFit",
          "price": 45.99,
          "img": ["https://example.com/images/chino-pants-front.jpg", "https://example.com/images/chino-pants-back.jpg"],
          "discount": 5,
          "category": "Pants"
        },
        {
          "id": "P018",
          "name": "High Waist Shorts",
          "description": "Trendy high waist shorts perfect for summer.",
          "size": ["S", "M", "L"],
          "brand": "SummerVibes",
          "price": 29.99,
          "img": ["https://example.com/images/high-waist-shorts-front.jpg", "https://example.com/images/high-waist-shorts-back.jpg"],
          "discount": 15,
          "category": "Shorts"
        },
        {
          "id": "P019",
          "name": "Puffer Jacket",
          "description": "Warm puffer jacket for cold weather.",
          "size": ["M", "L", "XL"],
          "brand": "WinterWarm",
          "price": 99.99,
          "img": ["https://example.com/images/puffer-jacket-front.jpg", "https://example.com/images/puffer-jacket-back.jpg"],
          "discount": 20,
          "category": "Jackets"
        },
        {
          "id": "P020",
          "name": "Floral Print Dress",
          "description": "Beautiful floral print dress for a summer look.",
          "size": ["S", "M", "L"],
          "brand": "BloomWear",
          "price": 54.99,
          "img": ["https://example.com/images/floral-dress-front.jpg", "https://example.com/images/floral-dress-back.jpg"],
          "discount": 10,
          "category": "Dresses"
        },
        {
          "id": "P021",
          "name": "Cotton Shorts",
          "description": "Soft and breathable cotton shorts for warm weather.",
          "size": ["S", "M", "L", "XL"],
          "brand": "CoolComfort",
          "price": 24.99,
          "img": ["https://example.com/images/cotton-shorts-front.jpg", "https://example.com/images/cotton-shorts-back.jpg"],
          "discount": 8,
          "category": "Shorts"
        },
        {
          "id": "P022",
          "name": "Knitted Cardigan",
          "description": "Cozy knitted cardigan with a relaxed fit.",
          "size": ["S", "M", "L", "XL"],
          "brand": "WarmKnits",
          "price": 49.99,
          "img": ["https://example.com/images/knitted-cardigan-front.jpg", "https://example.com/images/knitted-cardigan-back.jpg"],
          "discount": 12,
          "category": "Sweaters"
        },
        {
          "id": "P023",
          "name": "V-Neck T-Shirt",
          "description": "Comfortable V-neck t-shirt for everyday use.",
          "size": ["S", "M", "L", "XL"],
          "brand": "BasicWear",
          "price": 18.99,
          "img": ["https://example.com/images/v-neck-tshirt-front.jpg", "https://example.com/images/v-neck-tshirt-back.jpg"],
          "discount": 5,
          "category": "T-Shirts"
        },
        {
          "id": "P024",
          "name": "Slim Fit Chinos",
          "description": "Modern slim fit chinos for a sleek look.",
          "size": ["30", "32", "34", "36", "38"],
          "brand": "UrbanStyle",
          "price": 39.99,
          "img": ["https://example.com/images/slim-fit-chinos-front.jpg", "https://example.com/images/slim-fit-chinos-back.jpg"],
          "discount": 10,
          "category": "Pants"
        },
        {
          "id": "P025",
          "name": "Plaid Flannel Shirt",
          "description": "Classic plaid flannel shirt perfect for layering.",
          "size": ["S", "M", "L", "XL"],
          "brand": "FlannelHouse",
          "price": 34.99,
          "img": ["https://example.com/images/plaid-flannel-shirt-front.jpg", "https://example.com/images/plaid-flannel-shirt-back.jpg"],
          "discount": 10,
          "category": "Shirts"
        },
        {
          "id": "P026",
          "name": "Graphic Pullover Hoodie",
          "description": "Pullover hoodie with a bold graphic print.",
          "size": ["M", "L", "XL"],
          "brand": "StreetStyle",
          "price": 44.99,
          "img": ["https://example.com/images/graphic-hoodie-front.jpg", "https://example.com/images/graphic-hoodie-back.jpg"],
          "discount": 15,
          "category": "Hoodies"
        },
        {
          "id": "P027",
          "name": "Casual Linen Shirt",
          "description": "Lightweight linen shirt perfect for warm weather.",
          "size": ["S", "M", "L", "XL"],
          "brand": "BreezyWear",
          "price": 29.99,
          "img": ["https://example.com/images/linen-shirt-front.jpg", "https://example.com/images/linen-shirt-back.jpg"],
          "discount": 5,
          "category": "Shirts"
        },
        {
          "id": "P028",
          "name": "Faux Fur Coat",
          "description": "Luxurious faux fur coat for a chic winter look.",
          "size": ["M", "L", "XL"],
          "brand": "WinterGlam",
          "price": 99.99,
          "img": ["https://example.com/images/faux-fur-coat-front.jpg", "https://example.com/images/faux-fur-coat-back.jpg"],
          "discount": 18,
          "category": "Coats"
        },
        {
          "id": "P029",
          "name": "Jogging Sweatpants",
          "description": "Comfortable sweatpants for jogging or lounging.",
          "size": ["S", "M", "L", "XL"],
          "brand": "ActiveFit",
          "price": 29.99,
          "img": ["https://example.com/images/sweatpants-front.jpg", "https://example.com/images/sweatpants-back.jpg"],
          "discount": 10,
          "category": "Joggers"
        },
        {
          "id": "P030",
          "name": "Button-Up Blouse",
          "description": "Elegant button-up blouse with a feminine fit.",
          "size": ["S", "M", "L"],
          "brand": "FemmeStyle",
          "price": 39.99,
          "img": ["https://example.com/images/blouse-front.jpg", "https://example.com/images/blouse-back.jpg"],
          "discount": 12,
          "category": "Blouses"
        },
        {
          "id": "P031",
          "name": "High-Neck Sweater",
          "description": "Cozy high-neck sweater for chilly days.",
          "size": ["M", "L", "XL"],
          "brand": "CozyKnits",
          "price": 49.99,
          "img": ["https://example.com/images/high-neck-sweater-front.jpg", "https://example.com/images/high-neck-sweater-back.jpg"],
          "discount": 10,
          "category": "Sweaters"
        },
        {
          "id": "P032",
          "name": "Floral Maxi Dress",
          "description": "Flowy maxi dress with a vibrant floral print.",
          "size": ["S", "M", "L"],
          "brand": "BloomWear",
          "price": 59.99,
          "img": ["https://example.com/images/floral-maxi-dress-front.jpg", "https://example.com/images/floral-maxi-dress-back.jpg"],
          "discount": 15,
          "category": "Dresses"
        },
        {
          "id": "P033",
          "name": "Windbreaker Jacket",
          "description": "Lightweight windbreaker jacket with a hood.",
          "size": ["M", "L", "XL"],
          "brand": "OutdoorGear",
          "price": 59.99,
          "img": ["https://example.com/images/windbreaker-front.jpg", "https://example.com/images/windbreaker-back.jpg"],
          "discount": 10,
          "category": "Jackets"
        },
        {
          "id": "P034",
          "name": "Cotton Pajama Set",
          "description": "Soft cotton pajama set for a good night's sleep.",
          "size": ["S", "M", "L", "XL"],
          "brand": "SleepTight",
          "price": 34.99,
          "img": ["https://example.com/images/pajama-set-front.jpg", "https://example.com/images/pajama-set-back.jpg"],
          "discount": 8,
          "category": "Sleepwear"
        },
        {
          "id": "P035",
          "name": "Ripped Skinny Jeans",
          "description": "Trendy ripped skinny jeans for a casual look.",
          "size": ["28", "30", "32", "34", "36"],
          "brand": "UrbanStyle",
          "price": 49.99,
          "img": ["https://example.com/images/ripped-skinny-jeans-front.jpg", "https://example.com/images/ripped-skinny-jeans-back.jpg"],
          "discount": 15,
          "category": "Jeans"
        },
        {
          "id": "P036",
          "name": "Striped Polo Shirt",
          "description": "Classic striped polo shirt with a comfortable fit.",
          "size": ["S", "M", "L", "XL"],
          "brand": "CasualClassics",
          "price": 29.99,
          "img": ["https://example.com/images/striped-polo-shirt-front.jpg", "https://example.com/images/striped-polo-shirt-back.jpg"],
          "discount": 10,
          "category": "Polos"
        },
        {
          "id": "P037",
          "name": "Oversized Hoodie",
          "description": "Comfortable oversized hoodie for a relaxed look.",
          "size": ["M", "L", "XL"],
          "brand": "StreetStyle",
          "price": 44.99,
          "img": ["https://example.com/images/oversized-hoodie-front.jpg", "https://example.com/images/oversized-hoodie-back.jpg"],
          "discount": 20,
          "category": "Hoodies"
        },
        {
          "id": "P038",
          "name": "Pleated Skirt",
          "description": "Chic pleated skirt with a high-waist design.",
          "size": ["S", "M", "L"],
          "brand": "FemmeStyle",
          "price": 34.99,
          "img": ["https://example.com/images/pleated-skirt-front.jpg", "https://example.com/images/pleated-skirt-back.jpg"],
          "discount": 10,
          "category": "Skirts"
        },
        {
          "id": "P039",
          "name": "Baseball Cap",
          "description": "Casual baseball cap with an adjustable strap.",
          "size": ["One Size"],
          "brand": "CapWorld",
          "price": 19.99,
          "img": ["https://example.com/images/baseball-cap-front.jpg", "https://example.com/images/baseball-cap-back.jpg"],
          "discount": 5,
          "category": "Accessories"
        },
        {
          "id": "P040",
          "name": "Leather Belt",
          "description": "Genuine leather belt with a metal buckle.",
          "size": ["M", "L", "XL"],
          "brand": "BeltMasters",
          "price": 24.99,
          "img": ["https://example.com/images/leather-belt-front.jpg", "https://example.com/images/leather-belt-back.jpg"],
          "discount": 10,
          "category": "Accessories"
        },
        {
          "id": "P041",
          "name": "Chunky Sneakers",
          "description": "Fashionable chunky sneakers for a bold look.",
          "size": ["8", "9", "10", "11"],
          "brand": "SneakerFreak",
          "price": 74.99,
          "img": ["https://example.com/images/chunky-sneakers-front.jpg", "https://example.com/images/chunky-sneakers-back.jpg"],
          "discount": 15,
          "category": "Footwear"
        },
        {
          "id": "P042",
          "name": "Ankle Boots",
          "description": "Stylish ankle boots with a comfortable heel.",
          "size": ["6", "7", "8", "9"],
          "brand": "StepUp",
          "price": 89.99,
          "img": ["https://example.com/images/ankle-boots-front.jpg", "https://example.com/images/ankle-boots-back.jpg"],
          "discount": 20,
          "category": "Footwear"
        },
        {
          "id": "P043",
          "name": "Wool Scarf",
          "description": "Warm wool scarf with a soft texture.",
          "size": ["One Size"],
          "brand": "CozyKnits",
          "price": 29.99,
          "img": ["https://example.com/images/wool-scarf-front.jpg", "https://example.com/images/wool-scarf-back.jpg"],
          "discount": 10,
          "category": "Accessories"
        },
        {
          "id": "P044",
          "name": "Biker Jacket",
          "description": "Edgy biker jacket with a fitted design.",
          "size": ["S", "M", "L"],
          "brand": "UrbanRider",
          "price": 119.99,
          "img": ["https://example.com/images/biker-jacket-front.jpg", "https://example.com/images/biker-jacket-back.jpg"],
          "discount": 25,
          "category": "Jackets"
        },
        {
          "id": "P045",
          "name": "Cargo Pants",
          "description": "Functional cargo pants with multiple pockets.",
          "size": ["30", "32", "34", "36", "38"],
          "brand": "AdventureGear",
          "price": 49.99,
          "img": ["https://example.com/images/cargo-pants-front.jpg", "https://example.com/images/cargo-pants-back.jpg"],
          "discount": 10,
          "category": "Pants"
        },
        {
          "id": "P046",
          "name": "Denim Jacket",
          "description": "Classic denim jacket with a vintage wash.",
          "size": ["M", "L", "XL"],
          "brand": "DenimCo",
          "price": 79.99,
          "img": ["https://example.com/images/denim-jacket-front.jpg", "https://example.com/images/denim-jacket-back.jpg"],
          "discount": 15,
          "category": "Jackets"
        },
        {
          "id": "P047",
          "name": "Slim Fit Blazer",
          "description": "Tailored slim fit blazer for a sharp look.",
          "size": ["M", "L", "XL"],
          "brand": "ExecutiveStyle",
          "price": 129.99,
          "img": ["https://example.com/images/slim-fit-blazer-front.jpg", "https://example.com/images/slim-fit-blazer-back.jpg"],
          "discount": 20,
          "category": "Blazers"
        },
        {
          "id": "P048",
          "name": "Knitted Beanie",
          "description": "Cozy knitted beanie for winter warmth.",
          "size": ["One Size"],
          "brand": "WinterWarm",
          "price": 19.99,
          "img": ["https://example.com/images/knitted-beanie-front.jpg", "https://example.com/images/knitted-beanie-back.jpg"],
          "discount": 8,
          "category": "Accessories"
        },
        {
          "id": "P049",
          "name": "Sports Bra",
          "description": "Supportive sports bra for high-impact activities.",
          "size": ["S", "M", "L"],
          "brand": "FitActive",
          "price": 29.99,
          "img": ["https://example.com/images/sports-bra-front.jpg", "https://example.com/images/sports-bra-back.jpg"],
          "discount": 15,
          "category": "Activewear"
        },
        {
          "id": "P050",
          "name": "Lace-Up Boots",
          "description": "Durable lace-up boots for outdoor adventures.",
          "size": ["8", "9", "10", "11"],
          "brand": "TrailMaster",
          "price": 109.99,
          "img": ["https://example.com/images/lace-up-boots-front.jpg", "https://example.com/images/lace-up-boots-back.jpg"],
          "discount": 15,
          "category": "Footwear"
        }
      ]
      
]